### ISSUE TITLE
C++, Zip-архив

### ISSUE THREAD

**Issue by lockie** [sat2707/aicups#11]
Не складывается с отправкой решения в zip-архиве. Отправляю [архив](https://yadi.sk/d/CQjPsWJc3Mvo4D), в котором на верхнем уровне лежит `strategy.h` с кодом вида
```
работает вообще?
#include "my_strategy.hpp"
```
в результате никаких ошибок компиляции, решение можно выбрать. (На всякий случай, при компиляции локально такой код выдаёт пачку ошибок вида `error: stray '\321' in program`).

Перекладываю `strategy.h` в подкаталог `core` в архиве - тот же результат. 

Судя по поведению и набранным очкам, то, что при этом компилируется - это good baseline, т.е. ровно вот [это](https://github.com/sat2707/aicups/blob/master/clients/cpp11_client/client/core/strategy.h). Из чего напрашивается вывод, что будто бы архив распаковывается без перезаписи существующих файлов. Или, быть может, у меня где-то лыжи не едут?

**Comment by steleal** [comment]
Для Java и Python аналогичное поведение - на Python также заведен Issue.

**Comment by lockie** [comment]
Похоже, ошибка всё-таки не на клиентской стороне :)
На всякий случай сошлюсь на issue про Python: #16
