### ISSUE TITLE
Собственные игры в списке(отбор своих игр)

### ISSUE THREAD

**Issue by Erection** [sat2707/aicups#3]
Выделять в списке рейтинговых(нерейтинговых) игр свои игры, либо игры которые создали против твоей стратегии. Иметь возможность где-то (в личном кабинете) просматривать все созданные тобой игры, все игры которые были созданы против тебя.

**Comment by sat2707** [comment]
http://aicups.ru/profile/#unranked-games у себя в ЛК же можно посмотреть
