### ISSUE TITLE
Единообразие состояний лифта и пассажира

### ISSUE THREAD

**Issue by 678098** [sat2707/aicups#33]
> Коды состояний лифтов
> 
> ELEVATOR_STATE = {
> 'waiting': 0,
> 'moving': 1,
> 'opening': 2,
> 'filling': 3, # забирает и/или высаживает пассажиров
> 'closing': 4
> }
> Коды состояний пассажиров
> 
> PASSENGER_STATE = {
> 'waiting_for_elevator': 1, # ждет лифт
> 'moving_to_elevator': 2, # идет к лифту
> 'returning': 3, # возвращается обратно, если лифт уехал
> 'moving_to_floor': 4, # идет по лестнице
> 'using_elevator': 5, # едет в лифте
> 'exiting': 6, # выходит из лифта
> }

У лифта состояния нумеруются с 0, у пассажира - с 1.

**Comment by sat2707** [comment]
Не в этот раз, к сожалению. Сейчас менять `state`-ы уже стремно, в следующем чемпионате учтем
