### ISSUE TITLE
Чужие пассажиры не ждут 40 тиков

### ISSUE THREAD

**Issue by stremin** [sat2707/aicups#51]
Как только лифт открыл двери, в него сразу идут и свои и чужие пассажиры.

На примере игры 1550: на скриншоте в 1516 двери ещё закрыты, а в 1537 уже все идут к нему. С телефона не получилось сделать картинки соседних тиков,  но паузы нет.

Может быть 40 тиков сейчас отсчитываются с момента, когда лифт приехал на этаж? 

![screenshot_20170919-193142](https://user-images.githubusercontent.com/22256873/30604602-25958a88-9d74-11e7-9c59-4c47dab3620e.png)

![screenshot_20170919-193230](https://user-images.githubusercontent.com/22256873/30604613-2fa10d22-9d74-11e7-9d3e-0f3046e5636f.png)

**Comment by stremin** [comment]
При этом "Позвать пассажира в лифт можно лишь в состоянии 3", а к этому моменту уже прошло 100 тиков (> 40) от остановки.

**Comment by sat2707** [comment]
Да, действительно, эти 40 тиков отсчитываются параллельно с открытием дверей, а это в корне не верно. Спасибо, исправим

**Comment by sat2707** [comment]
Исправили
