### ISSUE TITLE
решить проблему карусели и счетчика тиков на одном этаже у пассажира

### ISSUE THREAD

**Issue by stalkermustang** [sat2707/aicups#55]
http://aicups.ru/session/3566

пассажиры не уходят с этажа по истечению 500 тиков. То есть счетчик не учитыает их движение к лифту, поэтоу возникает карусель, ибо все 6000 тиков пассажиры стоят на ОДНОМ этаже, хотя по правилам должны уходить с него при любых обстоятельствах через 500

**Comment by sat2707** [comment]
Вылечили
