### ISSUE TITLE
Пассажиру можно назначить лифт, который уже заполнен.

### ISSUE THREAD

**Issue by Daramant** [sat2707/aicups#59]
http://aicups.ru/session/3566
Пассажиру можно назначить лифт, который уже заполнен.
По идее, пассажир не должен идти к такому лифту.
Конечно возможен вариант, что, пока пассажир идет к лифту, из него кто-то успеет выйти,
но лучше не надо, т.к. так можно держать пассажиров.

**Comment by ivan-kudziev** [comment]
все норм да пассажиров можно держать, но только 500 тиков потом все уйдут на лесницу кто не влазил в лифт... так задумано

**Comment by sat2707** [comment]
Выкатили фикс, теперь можно звать новых пассажиров, пока лифт не заполнится. Те, которые уже шли к лифту до заполнения, дойдут до лифта и развернутся. Остальные просто не пойдут
