### ISSUE TITLE
Странности со временем состояний лифта

### ISSUE THREAD

**Issue by Oreshnik** [sat2707/aicups#61]
Игра http://aicups.ru/session_debug/5221/ правый игрок. По логу лифт с идентификатором 4 совершает переходы по состояниям:
2175-2216 filling (с 2176 он начинает получать команду идти на 4 этаж)
2217-2317 closing
2318 waiting
2319-2369 moving
2370-2470 opening.
Так как состояние приходило по эти шаги включительно, то получается что лифт находился в состояниях: filling 42 тика, closing - 101, moving - 51, opening 101.
Возможно что-то тут не так.

**Comment by sat2707** [comment]
Починили
