### ISSUE TITLE
Погрешности в вычислениях с плавающей запятой для Y пассажиров и лифтов

### ISSUE THREAD

**Issue by Mur4ik** [sat2707/aicups#78]
Пассажиры не всегда идут по лестнице заявленные 200 или 100 тиков, так как расчет прибытия на этаж вычисляется по "y" координате, получаем погрешности в +/- один тик.

Аналогичная ситуация с движением лифта.

Нужно эти операции привязывать к тикам, так как стратегии получают состояния на целочисленные "промежутки", так как текущая симуляция мира не соответствует документации.

**Comment by sat2707** [comment]
Починили, теперь явно тикает счетчик, описано в доке мира
