### ISSUE TITLE
условие задачи (подсчёт очков) написано непонятно

### ISSUE THREAD

**Issue by magicgoose** [sat2707/aicups#8]
http://aicups.ru/championships/

>    `За своего пассажира игрок получает (количество этажей)*10 очков`

>    `За пассажира противника игрок получает (количество этажей)*10*2 очков`

какие именно пассажиры имеются в виду и какие этажи?
без уточнений, это просто 2 константы, так как этажей 9 и пассажиров 200 независимо от действий игрока, судя по остальной части условия. получается, от игрока вообще ничего не зависит и всё это чистый рандом?

или дело в том, что надо читать условие в каком-то другом браузере, где появится скрытый для простых смертных текст? у меня Firefox, если что.

**Comment by plomovtsev** [comment]
Согласен, что написано не очень понятно, но логичнее всего предположить, что `кол-во этажей` -- это кол-во этажей на которые пассажир хотел и вышел из твоего лифта.

**Comment by magicgoose** [comment]
именно "хотел и вышел из твоего лифта"? или те, куда он дошёл пешком, тоже считаются?

**Comment by ivan-kudziev** [comment]
а может это разница между этажом где он сел и где вышел (по модулю естественно) * 10

**Comment by plomovtsev** [comment]
Да, судя по реплеям, учитывается разница 🐷

**Comment by sat2707** [comment]
Описали подробнее, спасибо
